### ISSUE TITLE
Explain why hellofx.Launcher-class is necessary

### ISSUE THREAD

**Issue by wlcrs** [openjfx/samples#17]
There is currently no explanation why the extra class `hellofx.Launcher` is necessary to launch non-modular JavaFX programs. Why is it not possible to use `hellofx.HelloFX` directly as main-class, why does that produce the error `Error: JavaFX runtime components are missing, and are required to run this application` ?

Because this isnt' properly documented, I spent a lot of time trying to figure out why I couldn't port my existing JavaFX-program..

**Comment by jperedadnr** [comment]
This is from the [docs](
https://openjfx.io/openjfx-docs/#modular) (section Non-Modular project):

> As explained [here](
http://mail.openjdk.java.net/pipermail/openjfx-dev/2018-June/021977.html), in order to create a runnable jar with all the required JavaFX dependencies, you will need to use a launcher class that doesn't extend from Application.

See a few  extra explanations [here](https://stackoverflow.com/questions/52569724/javafx-11-create-a-jar-file-with-gradle) and [here](https://stackoverflow.com/questions/52653836/maven-shade-javafx-runtime-components-are-missing).

**Comment by liudonghua123** [comment]
> This is from the [docs](https://openjfx.io/openjfx-docs/#modular) (section Non-Modular project):
> 
> > As explained [here](http://mail.openjdk.java.net/pipermail/openjfx-dev/2018-June/021977.html), in order to create a runnable jar with all the required JavaFX dependencies, you will need to use a launcher class that doesn't extend from Application.
> 
> See a few extra explanations [here](https://stackoverflow.com/questions/52569724/javafx-11-create-a-jar-file-with-gradle) and [here](https://stackoverflow.com/questions/52653836/maven-shade-javafx-runtime-components-are-missing).

I have the same problems, thanks for the explaination, it saved me a lot of time.
